# Generated by Django 5.2.5 on 2025-10-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_id", models.CharField(max_length=20)),
                ("equipment_code", models.CharField(max_length=20)),
                ("equipment_name_EN", models.CharField(max_length=100)),
                ("equipment_name_TH", models.CharField(max_length=100)),
                ("equipment_brand", models.CharField(max_length=100)),
                ("equipment_model", models.CharField(max_length=100)),
                ("equipment_sn", models.CharField(max_length=100)),
                ("equipment_gov", models.CharField(max_length=100)),
                ("equipment_price", models.IntegerField()),
                ("equipment_photo", models.CharField(max_length=100)),
                ("equipment_type", models.CharField(max_length=100)),
                ("equipment_life", models.IntegerField()),
                ("equipment_waranty_date", models.DateField()),
                ("equipment_waranty_due", models.DateField()),
                ("equipment_distributor_name", models.CharField(max_length=20)),
                ("equipment_distributor_tel", models.CharField(max_length=20)),
                ("equipment_sv_subunit", models.CharField(max_length=100)),
                ("equipment_sv_unit", models.CharField(max_length=100)),
                ("equipment_sv_department", models.CharField(max_length=100)),
                ("equipment_pm_fq", models.IntegerField()),
                ("equipment_pm_date", models.DateField()),
                ("equipment_pm_due", models.DateField()),
                ("equipment_cal_fq", models.IntegerField()),
                ("equipment_cal_date", models.DateField()),
                ("equipment_cal_due", models.DateField()),
                ("equipment_owner_unit", models.CharField(max_length=100)),
                ("equipment_owner_section", models.CharField(max_length=100)),
                ("equipment_owner_department", models.CharField(max_length=100)),
                ("equipment_owner_division", models.CharField(max_length=100)),
                ("equipment_owner_customer", models.CharField(max_length=100)),
                ("equipment_user_unit", models.CharField(max_length=100)),
                ("equipment_user_section", models.CharField(max_length=100)),
                ("equipment_user_department", models.CharField(max_length=100)),
                ("equipment_user_division", models.CharField(max_length=100)),
                ("equipment_user_customer", models.CharField(max_length=100)),
                ("equipment_register_username", models.CharField(max_length=100)),
                ("equipment_register_adminname", models.CharField(max_length=100)),
                ("equipment_register_date", models.DateField(auto_now_add=True)),
                ("equipment_note", models.CharField(max_length=300)),
            ],
        ),
    ]
