# Generated by Django 5.2.5 on 2025-10-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=20)),
                ("customer_units", models.CharField(max_length=100)),
                ("customer_section", models.CharField(max_length=100)),
                ("customer_department", models.CharField(max_length=100)),
                ("customer_division", models.CharField(max_length=100)),
                ("customer_customer", models.CharField(max_length=100)),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_tel", models.CharField(max_length=20)),
                ("customer_email", models.CharField(max_length=100)),
                ("customer_address", models.CharField(max_length=300)),
            ],
        ),
    ]
