# Generated by Django 5.2.5 on 2025-10-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0002_customer"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="Customer_list",
        ),
    ]
