# Generated by Django 5.2.5 on 2025-10-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0003_rename_customer_customer_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer_list",
            name="customer_semi_department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="equipment_list",
            name="equipment_owner_semi_department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="equipment_list",
            name="equipment_user_semi_department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
