# Generated by Django 5.2.5 on 2025-10-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0005_workorder_workorderattachment_workordercomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("code", models.CharField(blank=True, default="", max_length=50)),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order", "label"],
                "unique_together": {("category", "code")},
            },
        ),
    ]
