# Generated by Django 5.2.5 on 2025-10-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0006_masteritem"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="workorder_type",
            field=models.CharField(
                choices=[
                    ("repair", "ซ่อม"),
                    ("maintenance", "บำรุงรักษา"),
                    ("calibration", "สอบเทียบ"),
                    ("installation", "ติดตั้ง"),
                    ("consultation", "ให้คำปรึกษา"),
                    ("other", "อื่น ๆ"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
