# Generated by Django 5.2.5 on 2025-10-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0007_workorder_workorder_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment_list",
            name="requires_cal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="equipment_list",
            name="requires_pm",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="workorder_types",
            field=models.ManyToManyField(
                blank=True, related_name="workorders", to="cmms.masteritem"
            ),
        ),
    ]
