# Generated by Django 5.2.5 on 2025-10-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0008_equipment_list_requires_cal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="accepted_title_suggestion",
            field=models.BooleanField(default=False),
        ),
    ]
