# Generated by Django 5.2.5 on 2025-10-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0011_servicerequest_servicerequestattachment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masteritem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="cmms.masteritem",
            ),
        ),
    ]
