# Generated by Django 5.2.5 on 2025-10-15 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0012_masteritem_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_appointments",
                        to="cmms.equipment_list",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "equipment_type",
                    models.CharField(
                        help_text="Matches Equipment_list.equipment_type or MasterItem label/code",
                        max_length=100,
                    ),
                ),
                ("capacity", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["date", "equipment_type"],
                "unique_together": {("date", "equipment_type")},
            },
        ),
    ]
