# Generated by Django 5.2.5 on 2025-10-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0014_technician_technicianavailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="per_day_capacity",
            field=models.IntegerField(default=1),
        ),
    ]
