# Generated by Django 5.2.5 on 2025-10-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0015_technician_per_day_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="skills_m",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"category": "technician_skill"},
                related_name="technicians",
                to="cmms.masteritem",
            ),
        ),
    ]
