# Generated by Django 5.2.5 on 2025-10-20 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0021_move_skills_relations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="technician",
            name="skills_m",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"category": "equipments"},
                related_name="technicians",
                to="cmms.masteritem",
                verbose_name="ทักษะ / ประเภทอุปกรณ์",
            ),
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, unique=True, verbose_name="วันที่"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อวันหยุด")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="รายละเอียด"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="แก้ไขเมื่อ"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_holidays",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="สร้างโดย",
                    ),
                ),
            ],
            options={
                "verbose_name": "วันหยุดราชการ",
                "verbose_name_plural": "วันหยุดราชการ",
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["date", "is_active"], name="cmms_holida_date_09b86a_idx"
                    )
                ],
            },
        ),
    ]
