# Generated by Django 5.2.5 on 2025-10-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0022_alter_technician_skills_m_holiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="prefix_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mr", "นาย"),
                    ("mrs", "นาง"),
                    ("miss", "นางสาว"),
                    ("", "ไม่ระบุ"),
                ],
                default="",
                max_length=10,
                verbose_name="คำนำหน้า",
            ),
        ),
    ]
