# Generated by Django 5.2.5 on 2025-10-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0023_technician_prefix_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="prefix_name_custom",
            field=models.CharField(
                blank=True,
                default="",
                help_text='ใช้เมื่อเลือก "อื่นๆ (ระบุเอง)"',
                max_length=50,
                verbose_name="คำนำหน้า (ระบุเอง)",
            ),
        ),
        migrations.AlterField(
            model_name="technician",
            name="prefix_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "ไม่ระบุ"),
                    ("นาย", "นาย"),
                    ("นาง", "นาง"),
                    ("นางสาว", "นางสาว"),
                    ("ด.ช.", "ด.ช."),
                    ("ด.ญ.", "ด.ญ."),
                    ("other", "อื่นๆ (ระบุเอง)"),
                ],
                default="",
                max_length=50,
                verbose_name="คำนำหน้า",
            ),
        ),
    ]
