# Generated by Django 5.2.5 on 2025-10-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0024_technician_prefix_name_custom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="can_work_shifts",
            field=models.BooleanField(default=False, verbose_name="สามารถขึ้นเวรได้"),
        ),
        migrations.AlterField(
            model_name="technician",
            name="prefix_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "ไม่ระบุ"),
                    ("นาย", "นาย"),
                    ("นาง", "นาง"),
                    ("นางสาว", "นางสาว"),
                    ("other", "อื่นๆ (ระบุเอง)"),
                ],
                default="",
                max_length=50,
                verbose_name="คำนำหน้า",
            ),
        ),
    ]
