# Generated by Django 5.2.5 on 2025-10-28 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0025_technician_can_work_shifts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="วันที่")),
                (
                    "shift",
                    models.CharField(
                        choices=[("morning", "เวรเช้า"), ("afternoon", "เวรบ่าย")],
                        max_length=20,
                        verbose_name="เวร",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="หมายเหตุ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="แก้ไขเมื่อ"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shift_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="สร้างโดย",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_schedules",
                        to="cmms.technician",
                        verbose_name="ช่าง",
                    ),
                ),
            ],
            options={
                "verbose_name": "ตารางเวร",
                "verbose_name_plural": "ตารางเวร",
                "ordering": ["date", "shift"],
                "indexes": [
                    models.Index(
                        fields=["date", "shift"], name="cmms_shifts_date_8a7c6a_idx"
                    ),
                    models.Index(
                        fields=["technician", "date"],
                        name="cmms_shifts_technic_1976bc_idx",
                    ),
                ],
                "unique_together": {("date", "shift")},
            },
        ),
    ]
