# Generated by Django 5.2.5 on 2025-10-31 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmms", "0026_shiftschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Category Key",
                    ),
                ),
                ("label", models.CharField(max_length=200, verbose_name="ชื่อหมวดหมู่")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="คำอธิบาย"),
                ),
                (
                    "display_template",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Django template snippet (context: label, code, meta). Leave blank for default.",
                        verbose_name="Display Label Template",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Master Category",
                "verbose_name_plural": "Master Categories",
                "ordering": ["label"],
            },
        ),
        migrations.AddField(
            model_name="masteritem",
            name="meta",
            field=models.JSONField(
                blank=True, null=True, verbose_name="ข้อมูลเพิ่มเติม (Meta)"
            ),
        ),
        migrations.CreateModel(
            name="MasterFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Machine-safe name (lowercase, underscores, no spaces). e.g. "floor_number"',
                        max_length=100,
                        verbose_name="Field Name (machine key)",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=200, verbose_name="Label (แสดงใน UI)"),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("string", "String (text)"),
                            ("text", "Text (textarea)"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean (checkbox)"),
                            ("date", "Date"),
                            ("select", "Select (dropdown)"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="Field Type",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="Required (จำเป็น)"),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        help_text='JSON array of choices. e.g. ["A","B","C"] or [{"value":"a","label":"A"}]',
                        null=True,
                        verbose_name="Choices (for select type)",
                    ),
                ),
                (
                    "default_value",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Default Value",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order (ลำดับ)")),
                (
                    "help_text",
                    models.CharField(
                        blank=True, default="", max_length=400, verbose_name="Help Text"
                    ),
                ),
                (
                    "visible_in_preview",
                    models.BooleanField(
                        default=False, verbose_name="Visible in Preview"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="cmms.mastercategory",
                        verbose_name="หมวดหมู่",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Field Definition",
                "verbose_name_plural": "Master Field Definitions",
                "ordering": ["category", "order", "label"],
                "unique_together": {("category", "name")},
            },
        ),
    ]
