# Generated by Django 5.2.5 on 2025-11-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0027_mastercategory_masteritem_meta_masterfielddefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_list',
            name='equipment_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
