# Generated by Django 5.2.5 on 2025-12-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0040_equipment_history_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTaskDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('maintenance', 'Maintenance / PM'), ('calibration', 'Calibration'), ('repair', 'Repair')], max_length=30, unique=True)),
                ('hours', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
            options={
                'verbose_name': 'Default maintenance task duration',
                'verbose_name_plural': 'Default maintenance task durations',
            },
        ),
        migrations.AddField(
            model_name='equipment_list',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ป้อนจำนวนชั่วโมงที่คาดว่าใช้ต่อชิ้น (เช่น 1.5)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='equipment_list',
            name='equipment_service_provider',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
