# Generated by Django 5.2.5 on 2026-01-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0042_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='customer_department',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_position',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_telephone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
