# Generated by Django 4.2.25 on 2026-01-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0043_servicerequest_customer_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('other', 'ทั่วไป'), ('maintenance', 'ซ่อมบำรุง'), ('calibration', 'ปรับเทียบ'), ('inspection', 'ตรวจสอบ'), ('installation', 'ติดตั้ง')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed by officer'), ('converted', 'Converted to WorkOrder'), ('rejected', 'Rejected'), ('deleted', 'Deleted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
