# Generated by Django 5.2.5 on 2026-01-29 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0044_servicerequest_request_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='workorder_documents/')),
                ('kind', models.CharField(choices=[('CERT_XLS', 'Cert XLS (ช่าง)'), ('CERT_PDF', 'Cert PDF (TM)'), ('ATTACHMENT', 'เอกสารแนบ')], default='ATTACHMENT', max_length=20)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('mime', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'เอกสาร',
                'verbose_name_plural': 'เอกสาร',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list, verbose_name='รายการ')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคารวม')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ภาษี')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคารวมสุทธิ')),
                ('terms', models.TextField(blank=True, default='', verbose_name='เงื่อนไข')),
                ('estimate_days', models.IntegerField(default=0, verbose_name='ระยะเวลาดำเนินการ (วัน)')),
                ('expire_at', models.DateField(blank=True, null=True, verbose_name='หมดอายุ')),
                ('status', models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติ'), ('REJECTED', 'ปฏิเสธ')], default='PENDING', max_length=20, verbose_name='สถานะ')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ใบเสนอราคา',
                'verbose_name_plural': 'ใบเสนอราคา',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='รายละเอียด')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='จำนวน')),
                ('unit', models.CharField(default='ชิ้น', max_length=50, verbose_name='หน่วย')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคาต่อหน่วย')),
                ('item_type', models.CharField(choices=[('PART', 'อะไหล่'), ('LABOR', 'ค่าแรง'), ('SERVICE', 'ค่าบริการ'), ('OTHER', 'อื่นๆ')], default='PART', max_length=20, verbose_name='ประเภท')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='หมายเหตุ')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='cmms.quotation')),
            ],
            options={
                'verbose_name': 'รายการใบเสนอราคา',
                'verbose_name_plural': 'รายการใบเสนอราคา',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('APPOINTMENT_PM', 'นัดหมาย PM (Preventive Maintenance)'), ('APPOINTMENT_CAL', 'นัดหมาย Calibration'), ('REPAIR', 'แจ้งซ่อม'), ('INSTALL', 'ติดตั้ง'), ('CONSULT', 'ให้คำปรึกษา'), ('OTHER', 'อื่นๆ')], default='OTHER', max_length=20, verbose_name='ประเภทคำขอ')),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'รอตรวจสอบ'), ('NEED_CUSTOMER_CONFIRM', 'รอลูกค้ายืนยัน'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ถูกปฏิเสธ (Admin)'), ('REJECTED_BY_CUSTOMER', 'ถูกปฏิเสธ (ลูกค้า)'), ('WORK_ORDER_CREATED', 'สร้างใบงานแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PENDING_REVIEW', max_length=30, verbose_name='สถานะ')),
                ('equipment_detail', models.TextField(blank=True, default='', verbose_name='รายละเอียดอุปกรณ์เพิ่มเติม')),
                ('appointment_slot', models.DateTimeField(blank=True, null=True, verbose_name='วัน-เวลานัดหมาย')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='ยอมรับเงื่อนไข')),
                ('symptoms', models.TextField(blank=True, default='', verbose_name='อาการ/ปัญหา')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('description', models.TextField(blank=True, default='', verbose_name='รายละเอียด')),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_email', models.CharField(blank=True, default='', max_length=200)),
                ('customer_telephone', models.CharField(blank=True, default='', max_length=50)),
                ('customer_department', models.CharField(blank=True, default='', max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('rejected_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_requests_v2', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests_v2', to='cmms.equipment_list', verbose_name='อุปกรณ์')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests_v2', to=settings.AUTH_USER_MODEL, verbose_name='ตรวจสอบโดย')),
            ],
            options={
                'verbose_name': 'คำขอรับบริการ (V2)',
                'verbose_name_plural': 'คำขอรับบริการ (V2)',
                'ordering': ['-created_at'],
                'permissions': [('can_review_request', 'Can review service requests'), ('can_approve_request', 'Can approve service requests')],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestLogV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cmms.servicerequestv2')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestAttachmentV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_attachments', to='cmms.document')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cmms.servicerequestv2')),
            ],
            options={
                'verbose_name': 'เอกสารแนบคำขอ',
                'verbose_name_plural': 'เอกสารแนบคำขอ',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PM', 'Preventive Maintenance'), ('CAL', 'Calibration'), ('REPAIR', 'ซ่อม'), ('INSTALL', 'ติดตั้ง'), ('CONSULT', 'ให้คำปรึกษา'), ('OTHER', 'อื่นๆ')], default='OTHER', max_length=20, verbose_name='ประเภทงาน')),
                ('status', models.CharField(choices=[('QUEUED', 'รอคิว'), ('ASSIGNED', 'มอบหมายแล้ว'), ('TECH_ACCEPTED', 'ช่างรับงานแล้ว'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('PMCAL_AWAITING_CERT', 'รอใบรับรอง'), ('TM_CERT_CHECK', 'TM ตรวจสอบ Cert'), ('LM_APPROVAL', 'รอ LM อนุมัติ'), ('DIAGNOSING', 'กำลังวินิจฉัย'), ('QUOTATION_PENDING', 'รอใบเสนอราคา'), ('QUOTATION_APPROVED', 'ใบเสนอราคาอนุมัติแล้ว'), ('QUOTATION_REJECTED', 'ใบเสนอราคาถูกปฏิเสธ'), ('FIXING', 'กำลังซ่อม'), ('VERIFYING', 'ตรวจสอบผลงาน'), ('READY_FOR_RETURN', 'พร้อมคืนเครื่อง'), ('CLOSED', 'ปิดงานแล้ว'), ('CANCELLED', 'ยกเลิก'), ('CONVERTED_TO_REPAIR', 'แปลงเป็นงานซ่อม')], default='QUEUED', max_length=30, verbose_name='สถานะ')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('description', models.TextField(blank=True, default='', verbose_name='รายละเอียด')),
                ('pmcal_result', models.CharField(blank=True, choices=[('NORMAL', 'ปกติ'), ('NEED_TM_OPINION', 'ต้องการความเห็น TM')], max_length=20, null=True, verbose_name='ผล PM/CAL')),
                ('diagnosis', models.TextField(blank=True, default='', verbose_name='การวินิจฉัย')),
                ('root_cause', models.CharField(blank=True, choices=[('AGING', 'อายุการใช้งาน'), ('OVERLOAD', 'ใช้งานเกินกำลัง'), ('POOR_QUALITY', 'คุณภาพชิ้นส่วน'), ('MISUSE', 'ใช้งานผิดวิธี'), ('ENVIRONMENT', 'สภาพแวดล้อม'), ('OTHER', 'อื่นๆ')], max_length=20, null=True, verbose_name='สาเหตุ')),
                ('action_plan', models.TextField(blank=True, default='', verbose_name='แผนการซ่อม')),
                ('parts_json', models.JSONField(blank=True, null=True, verbose_name='อะไหล่ที่ใช้ (JSON)')),
                ('recurrence_risk', models.CharField(blank=True, choices=[('NONE', 'ไม่มีความเสี่ยง'), ('HAS_RISK', 'มีความเสี่ยง')], max_length=20, null=True, verbose_name='ความเสี่ยงเกิดซ้ำ')),
                ('prevention_plan', models.TextField(blank=True, default='', verbose_name='แผนป้องกัน')),
                ('lm_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_workorders', to=settings.AUTH_USER_MODEL, verbose_name='ช่างผู้รับผิดชอบ')),
                ('assigned_tm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tm_workorders', to=settings.AUTH_USER_MODEL, verbose_name='TM ผู้รับผิดชอบ')),
                ('cert_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_pdf_workorders', to='cmms.document', verbose_name='Cert PDF')),
                ('cert_xls', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_xls_workorders', to='cmms.document', verbose_name='Cert XLS')),
                ('converted_from_wo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_to_repairs', to='cmms.workorderv2', verbose_name='แปลงมาจาก WO')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workorders_v2', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders_v2', to='cmms.equipment_list')),
                ('lm_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lm_approved_workorders', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders', to='cmms.servicerequestv2')),
            ],
            options={
                'verbose_name': 'ใบสั่งงาน (V2)',
                'verbose_name_plural': 'ใบสั่งงาน (V2)',
                'ordering': ['-created_at'],
                'permissions': [('can_assign_tm', 'Can assign TM to work orders'), ('can_assign_tech', 'Can assign technician to work orders'), ('can_upload_cert_xls', 'Can upload cert XLS'), ('can_upload_cert_pdf', 'Can upload cert PDF'), ('can_approve_lm', 'Can approve as Line Manager'), ('can_convert_to_repair', 'Can convert PM/CAL to repair')],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderLogV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cmms.workorderv2')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='servicerequestv2',
            name='converted_to_workorder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_request', to='cmms.workorderv2'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='workorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='cmms.workorderv2'),
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CMU_SCAN', 'CMU Scan'), ('SIGN', 'ลายเซ็น')], max_length=20, verbose_name='วิธีการ')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='ชื่อผู้รับ')),
                ('receiver_id', models.CharField(blank=True, default='', max_length=50, verbose_name='รหัสผู้รับ')),
                ('time', models.DateTimeField(verbose_name='เวลาคืน')),
                ('scan_ref', models.CharField(blank=True, default='', max_length=200, verbose_name='CMU Scan Reference')),
                ('signature_ref', models.TextField(blank=True, default='', verbose_name='Signature Reference')),
                ('note', models.TextField(blank=True, default='', verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='cmms.workorderv2')),
            ],
            options={
                'verbose_name': 'การคืนเครื่อง',
                'verbose_name_plural': 'การคืนเครื่อง',
                'ordering': ['-created_at'],
            },
        ),
    ]
