# Generated by Django 5.2.5 on 2026-03-24 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0047_add_technician_fk_to_workorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='technician',
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='รหัสอะไหล่')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่ออะไหล่')),
                ('description', models.TextField(blank=True, default='', verbose_name='รายละเอียด')),
                ('unit', models.CharField(blank=True, default='ชิ้น', max_length=50, verbose_name='หน่วยนับ')),
                ('quantity', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
                ('min_quantity', models.IntegerField(default=0, help_text='แจ้งเตือนเมื่อจำนวนคงเหลือต่ำกว่านี้', verbose_name='จำนวนขั้นต่ำ')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ราคาต่อหน่วย (บาท)')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='ตำแหน่งจัดเก็บ')),
                ('supplier', models.CharField(blank=True, default='', max_length=200, verbose_name='ผู้จำหน่าย')),
                ('active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('notes', models.TextField(blank=True, default='', verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('category', models.ForeignKey(blank=True, help_text='เลือกจาก Master Data (หมวดหมู่อะไหล่)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='cmms.masteritem', verbose_name='หมวดหมู่')),
                ('compatible_equipment', models.ManyToManyField(blank=True, related_name='spare_parts', to='cmms.equipment_list', verbose_name='อุปกรณ์ที่ใช้ร่วมได้')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spare_parts', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_spare_parts', to=settings.AUTH_USER_MODEL, verbose_name='แก้ไขโดย')),
            ],
            options={
                'verbose_name': 'อะไหล่',
                'verbose_name_plural': 'อะไหล่',
                'ordering': ['code'],
            },
        ),
    ]
