# Generated by Django 5.2.5 on 2026-03-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0048_remove_workorder_technician_sparepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='equipment_meta',
            field=models.JSONField(blank=True, default=dict, help_text='{"equipment_names":[],"equipment_brands":[],"equipment_models":[]}', verbose_name='ข้อมูลเครื่องมือที่ใช้งาน'),
        ),
    ]
