# Generated by Django 5.2.5 on 2026-04-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0049_add_equipment_meta_to_sparepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวนที่เบิก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder_usages', to='cmms.sparepart')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_spare_parts', to='cmms.workorder')),
            ],
            options={
                'verbose_name': 'อะไหล่ที่ใช้ในใบงาน',
                'verbose_name_plural': 'อะไหล่ที่ใช้ในใบงาน',
                'ordering': ['id'],
                'unique_together': {('workorder', 'spare_part')},
            },
        ),
    ]
