# Generated by Django 5.2.5 on 2026-04-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0050_add_workorder_sparepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordersparepart',
            name='is_out_of_stock',
            field=models.BooleanField(default=False, help_text='อะไหล่ไม่มีในคลัง ต้องทำเรื่องจัดซื้อ', verbose_name='รอจัดซื้อ'),
        ),
    ]
