# Generated by Django 5.2.5 on 2026-04-01 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0051_add_out_of_stock_to_workordersparepart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workordersparepart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workordersparepart',
            name='custom_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ชื่ออะไหล่ (อื่นๆ)'),
        ),
        migrations.AddField(
            model_name='workordersparepart',
            name='custom_unit',
            field=models.CharField(blank=True, default='ชิ้น', max_length=50, verbose_name='หน่วยนับ (อื่นๆ)'),
        ),
        migrations.AddField(
            model_name='workordersparepart',
            name='custom_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ราคาต่อหน่วย (อื่นๆ)'),
        ),
        migrations.AlterField(
            model_name='workordersparepart',
            name='spare_part',
            field=models.ForeignKey(blank=True, help_text='เลือกจากคลัง หรือเว้นว่างสำหรับอะไหล่อื่นๆ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorder_usages', to='cmms.sparepart'),
        ),
    ]
