# Generated by Django 5.2.5 on 2026-04-07 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0052_add_custom_spare_part_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='follow_up_for',
            field=models.ForeignKey(blank=True, help_text='ลิงก์กลับไปหาใบงานต้นเรื่องที่มีอะไหล่ค้าง', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_orders', to='cmms.workorder', verbose_name='ใบงานต้นเรื่อง'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='follow_up_needed',
            field=models.BooleanField(default=False, help_text='ใบงานเสร็จแล้ว แต่มีอะไหล่รอจัดซื้อ — เมื่ออะไหล่มาจะสร้างใบงานติดตาม', verbose_name='ต้องติดตาม'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='hold_note',
            field=models.TextField(blank=True, default='', verbose_name='หมายเหตุการระงับ'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='hold_reason',
            field=models.CharField(blank=True, choices=[('waiting_parts', 'รออะไหล่'), ('waiting_outsource', 'รอผู้ให้บริการภายนอก'), ('other', 'อื่นๆ')], default='', max_length=30, verbose_name='เหตุผลการระงับ'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='outsource_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ค่าใช้จ่าย Outsource'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='outsource_expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่คาดว่า Outsource เสร็จ'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='outsource_vendor',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ผู้ให้บริการภายนอก'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('verified', 'Verified'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
