# Generated by Django 5.2.5 on 2026-04-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0053_add_on_hold_follow_up_outsource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='hold_note',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='hold_reason',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='outsource_cost',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='outsource_expected_date',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='outsource_vendor',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
