# Generated by Django 5.2.5 on 2026-04-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0054_remove_on_hold_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='hold_note',
            field=models.TextField(blank=True, default='', verbose_name='หมายเหตุการระงับ'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='hold_reason',
            field=models.CharField(blank=True, choices=[('waiting_parts', 'รออะไหล่'), ('waiting_outsource', 'รอผู้ให้บริการภายนอก'), ('other', 'อื่นๆ')], default='', max_length=30, verbose_name='เหตุผลการระงับ'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='outsource_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ค่าใช้จ่าย Outsource'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='outsource_expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่คาดว่า Outsource เสร็จ'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='outsource_vendor',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ผู้ให้บริการภายนอก'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('verified', 'Verified'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
