# Generated by Django 5.2.5 on 2026-05-06 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0055_restore_on_hold_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_list',
            name='equipment_type_master',
            field=models.ForeignKey(blank=True, help_text='เชื่อมโยงกับ MasterItem category=equipments เพื่อจับคู่ทักษะช่าง', limit_choices_to={'category': 'equipments'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='cmms.masteritem', verbose_name='ประเภทอุปกรณ์ (Master)'),
        ),
    ]
