# Generated by Django 4.2.25 on 2026-05-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0057_workorderattachment_document_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_list',
            name='equipment_type_master',
        ),
        migrations.AlterField(
            model_name='workorderattachment',
            name='document_type',
            field=models.CharField(choices=[('pm_report', 'รายงานผลการบำรุงรักษา'), ('cal_report', 'รายงานผลการสอบเทียบ'), ('repair_report', 'รายงานผลงานซ่อม'), ('other', 'อื่นๆ')], default='other', max_length=20),
        ),
    ]
