# Generated by Django 4.2.25 on 2026-07-08 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0058_update_attachment_document_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceappointment',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='cmms.technician', verbose_name='ช่างที่ได้รับมอบหมาย'),
        ),
        migrations.AlterField(
            model_name='workorderattachment',
            name='document_type',
            field=models.CharField(choices=[('pm_report', 'รายงานผลการบำรุงรักษา'), ('cal_report', 'รายงานผลการสอบเทียบ'), ('repair_report', 'รายงานผลการซ่อม'), ('other', 'อื่นๆ')], default='other', max_length=20),
        ),
    ]
