# Generated by Django 5.2.5 on 2026-09-03 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0060_alter_profile_options_profile_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อแบบฟอร์ม')),
                ('equipment_type', models.CharField(blank=True, default='', help_text='เว้นว่างเพื่อใช้เป็นแบบฟอร์มกลางสำหรับทุกประเภทเครื่องมือ', max_length=100, verbose_name='ประเภทเครื่องมือ')),
                ('workorder_type', models.CharField(choices=[('repair', 'ซ่อม'), ('maintenance', 'บำรุงรักษา'), ('calibration', 'สอบเทียบ'), ('installation', 'ติดตั้ง'), ('consultation', 'ให้คำปรึกษา'), ('other', 'อื่น ๆ')], max_length=50, verbose_name='ประเภทใบงาน')),
                ('description', models.TextField(blank=True, default='', verbose_name='คำอธิบาย')),
                ('active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'แบบฟอร์ม Checklist',
                'verbose_name_plural': 'แบบฟอร์ม Checklist',
                'ordering': ['workorder_type', 'equipment_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('name', models.CharField(max_length=255, verbose_name='รายการตรวจสอบ')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='คำอธิบายเพิ่มเติม')),
                ('result_type', models.CharField(choices=[('check', 'ตรวจสอบ (ผ่าน/ไม่ผ่าน/N-A)'), ('measurement', 'วัดค่า (เทียบค่ามาตรฐาน + ค่าเผื่อเบี่ยงเบน)'), ('text', 'กรอกข้อความ/หมายเหตุ')], default='check', max_length=20, verbose_name='รูปแบบการกรอกผล')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='หน่วย')),
                ('standard_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='ค่ามาตรฐาน/ค่าอ้างอิง')),
                ('tolerance', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='ค่าเผื่อเบี่ยงเบน (±)')),
                ('is_required', models.BooleanField(default=True, verbose_name='ต้องกรอก')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cmms.checklisttemplate')),
            ],
            options={
                'verbose_name': 'รายการใน Checklist',
                'verbose_name_plural': 'รายการใน Checklist',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklists', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workorder_checklists', to='cmms.checklisttemplate')),
                ('workorder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='cmms.workorder')),
            ],
            options={
                'verbose_name': 'Checklist ของใบงาน',
                'verbose_name_plural': 'Checklist ของใบงาน',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderChecklistResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_choice', models.CharField(blank=True, choices=[('pass', 'ผ่าน'), ('fail', 'ไม่ผ่าน'), ('na', 'N/A')], default='', max_length=10)),
                ('measured_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_pass', models.BooleanField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='cmms.workorderchecklist')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='cmms.checklisttemplateitem')),
            ],
            options={
                'verbose_name': 'ผลการกรอก Checklist รายข้อ',
                'verbose_name_plural': 'ผลการกรอก Checklist รายข้อ',
                'ordering': ['template_item__order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['workorder_type', 'equipment_type', 'active'], name='cmms_checkl_workord_7d4261_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workorderchecklistresult',
            unique_together={('checklist', 'template_item')},
        ),
    ]
