# Generated by Django 5.2.5 on 2026-09-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0061_checklisttemplate_checklisttemplateitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplate',
            name='equipment_type',
            field=models.CharField(blank=True, default='', help_text='เว้นว่างเพื่อใช้เป็นแบบฟอร์มกลางสำหรับทุกประเภทเครื่องมือ', max_length=500, verbose_name='ประเภทเครื่องมือ'),
        ),
    ]
