# Generated by Django 5.2.5 on 2026-09-03 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0062_alter_checklisttemplate_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='replaced_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='cmms.checklisttemplate', verbose_name='ถูกแทนที่ด้วยเวอร์ชัน'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='เวอร์ชัน'),
        ),
    ]
